### ISSUE TITLE
new module: FastQ-Screen

### ISSUE THREAD

**Issue by JPejovicApis** [nf-core/modules#3157] opened 2023-03-28 08:28 UTC

**Comment by JPejovicApis** [comment] 2023-03-29 11:19
Hello, we continued our work on Fastq Screen  today as well. @snesic @ewels do you agree to move discussion from slack over here since it will be easier to follow once hackathon is over? And Phil if you could add Steven Wingett?

**Comment by ewels** [comment] 2023-03-29 12:40
🎉  @StevenWingett 📢

**Comment by snesic** [comment] 2023-03-29 13:54
## Use cases for fastq screen. 
1. Use iGenomes species (allow user to select some of them or all)
2. User would provide a list of fasta files (ribosomal, globin, phyx,...)
3. Combination of 1 and 2



## Modules: 
1. create database
2. run fastq_screen


### Create database

After checking the docu, `fastq screen` does not have a script to create config but it describes how it should be created using bowtie (or bwa) aligner. Therefore, as @ewels mentioned, we could use `BOWTIE2_BUILD` and then pass it to `FASTQ_SCREEN_BUILD`. 

We would:
1. Create `FASTQ_SCREEN_BUILD` module that takes a list of bowtie indexes (mix of species) and outputs a folder with them and the config file. 
2. hard-code aligner to bowtie2
3. create tests: output of `BOWTIE2_BUILD` -> input to `FASTQ_SCREEN_BUILD`


Issues: 
1. `BOWTIE2_BUILD` outputs `BOWTIE2_BUILD.out.index` which a folder called bowtie2 and contains indexes. If different species have the same name (genome.fa) it won't work. 



### Create fastq screen

Input: 
1. Folder with indexes for each genome and config file
2. Sample fastqs 

Tests: 

Use output from `FASTQ_SCREEN_BUILD` as database and test fastq files

**Comment by StevenWingett** [comment] 2023-04-03 14:49
Hi,

I'm not sure if this is of any use, but FastQ Screen has the command line option "--add_genome".  This option edits the file "fastq_screen.conf" (in the folder where the FastQ Screen script is saved) to add a new genome.   The command takes a comma separated list of: Database name, Genome path + basename, notes.

Thanks,
Steven

**Comment by snesic** [comment] 2023-04-03 15:45
> Hi,
> 
> I'm not sure if this is of any use, but FastQ Screen has the command line option "--add_genome". This option edits the file "fastq_screen.conf" (in the folder where the FastQ Screen script is saved) to add a new genome. The command takes a comma separated list of: Database name, Genome path + basename, notes.
> 
> Thanks, Steven

To create a config file is easy. The problem is to pass bowtie index folder/files to a nextflow process.  If `FASTQ_SCREEN_BUILD` takes a list of folders with bowtie index files, we will have *nextflow input file name collision* as in iGenomes these folders are called the same, `Bowtie2Index`. Moreover, index files are called genome.[1-5]... 

The same problem would happen if we use `BOWTIE2_BUILD` as it outputs a hard-coded folder name `bowtie2`. 

We could either 
1. create additional process that would rename `bowtie2` or `Bowtie2Index` (to reference name) and then call `FASTQ_SCREEN_BUILD`. 
2. create a folder somewhere in s3 that would contain soft links to iGenomes bowtie folders but with species names are folder names. 

Is there any other way we could solve this,  @ewels  @SPPearce ?

**Comment by SPPearce** [comment] 2023-04-03 16:35
Files can be staged into subfolders if that helps, with automatic numbering. Not sure if it can be a subfolder based on the meta map for instance.
bowtie2/build could potentially be updated to not hardcode the output folder, perhaps using task.ext.prefix, which might be the neater way of solving that

**Comment by SPPearce** [comment] 2023-04-03 16:39
That could either rename the folder or the individual genome files - would it cause an issue if the index files didn't have the same prefix as the fasta? My gut says it probably would, so renaming the folder could be a nice way to deal with that

**Comment by snesic** [comment] 2023-04-06 07:05
It should not as the index files already contain fasta/reference but yes, it easier to rename just the folder rather than multiple files.. 

As some of you mentioned, `stageAs` would be a nice solution but I don't know if it would work with a list of files (list of stage names)..

**Comment by ewels** [comment] 2023-04-21 10:34
Thank you @tdanhorn 👍🏻  That's an interesting point. As a first iteration I guess that we could get the module to be skipped at pipeline level / exit silently if no config is given.

Note that this approach won't work for anyone running on cloud, as it will be using files outside of the work directory scope. Maybe problematic also for people using containers, depending on bind path settings. So it would have some pretty major limitations.

**Comment by snesic** [comment] 2023-04-27 07:57
@ewels , @SPPearce we have a [build config script, please check the code here](https://github.com/JPejovicApis/modules/blob/fastq_screen/modules/nf-core/fastqscreen/buildfromindex/main.nf) and it works fine locally but we have a problem running nf-core module tests. 

What happens is: 
*versions.yml is ill-formatted*

The reason for that is:
Line 78 creates a content for config file. It is then passed with echo (line 86). When nextflow creates `.command.sh` all lines are indented and then *versions.yml* is ill-formatted. This happens becase we have `\n` in the string.. The config file is however properly created.. 

Is this a nextflow issue?

**Comment by ewels** [comment] 2023-05-02 14:32
> Process `RENAME_PATH`

You don't need a process to do this - just use `stageAs` ([docs](https://nextflow.io/docs/latest/process.html#input-type-path)). The same is true with most of the file copying in the `FASTQSCREEN_BUILDFROMINDEX` process, I think.

I'm a little lost with the formatting error, but you have quite a bit of whitespace in a range of places.
For example, `.join(' \n\n ')` surrounds a double newline with spaces. Maybe you mean `.join("\n\n")`?

**Comment by ewels** [comment] 2023-05-03 21:48
I'm not able to replicate any problem..

`main.nf`:
```nextflow
process TEST_INDENT{
    script:
    """
    touch test.txt
    echo "Hello \n World" >> test.txt
    touch test.txt
    """
}
workflow {
    TEST_INDENT()
}
```

Running the workflow:
```console
❯ nextflow run main.nf
N E X T F L O W  ~  version 23.04.0
Launching `main.nf` [thirsty_laplace] DSL2 - revision: 03b5175adf
executor >  local (1)
[17/e68df5] process > TEST_INDENT [100%] 1 of 1 ✔
```

Viewing the created file:
```console
❯ cat work/17/e68df5e76f90e711c1f6e1b3e4582f/test.txt
Hello
World
```

No indentation in the file..

**Comment by snesic** [comment] 2023-05-04 07:22
Yes, there is no problem with the script (same as for fastqscreen build) but with the test that checks version and the problem is caused by this indentation. If you would do `cat work/17/e68df5e76f90e711c1f6e1b3e4582f/test/.command.sh`, you would see:

```
#!/bin/bash -ue
touch test.txt
   echo 'Hello 
World' >> test.txt
   touch test.txt

```

This indent does not affect the script but affects the part that collects version:

```
cat <<-END_VERSIONS > versions.yml
    "${task.process}":
        bla: 0.1
END_VERSIONS
```
Therefore the test will fail.

**Comment by wzheng0520** [comment] 2023-07-28 03:48
Hi,

I want to know does anyone have idea about how to run fastqscreen on cloud like aws batch? Seems like if we want to run it on aws batch which would be impossible for right now?

**Comment by nevinwu** [comment] 2023-08-25 11:56
Hi all, I was wondering what was the state of this new FastQ-Screen module, since I am interested in using this module in a Nextflow pipeline.

**Comment by nevinwu** [comment] 2023-08-25 12:02
Hi all, I was wondering what is the state of this new FastQ-Screen module, since I am interested in using it in a pipeline.

I have seen PR #3574, but it seems that some checks were not successful.

**Comment by snesic** [comment] 2023-08-25 18:03
@nevinwu, thanks for your interest. The test to detect the version fails because `nextflow` introduces indentation in `versions.yml`. Other than that, everything works fine.

Once we get this module merged, we could create a workflow that generates the database and runs FastQ-Screen.

**Closed** 2024-05-03 05:38 UTC
Labels: hackathon2023
