### ISSUE TITLE
new module: PretextMap

### ISSUE THREAD

**Issue by priyanka-surana** [nf-core/modules#1241] opened 2022-01-27 16:25 UTC
I think it would be good to have a module for PretextMap(https://github.com/wtsi-hpag/PretextMap). This tool is used for HiC contact map visualisation.

- This module does not exist yet with the [`nf-core modules list`](https://github.com/nf-core/tools#list-modules) command
- There is no [open pull request](https://github.com/nf-core/modules/pulls) for this module
- There is no [open issue](https://github.com/nf-core/modules/issues) for this module
- I'm planning to work on this module, so I added myself to the `Assignees` to facilitate tracking who is working on the module

**Comment by muffato** [comment] 2022-11-04 12:00
Duplicate of #1947

**Closed by muffato** 2022-11-04 12:00 UTC
